version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "chore:"
    groups:
      cargo:
        patterns:
          - "*"
    versioning-strategy: "increase-if-necessary"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "chore:"
    groups:
      github-actions:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
