version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "chore:"
    assignees:
      - "frazzer951"
    groups:
      cargo:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "chore:"
    assignees:
      - "frazzer951"
    versioning-strategy: "increase-if-necessary"
    groups:
      github-actions:
        patterns:
          - "*"
