[package]
authors     = ["Luke Eltiste"]
description = "A collection of command line tool that I use to make my life easier"
edition     = "2021"
license     = "MIT"
name        = "frazzers-utils"
readme      = "README.md"
repository  = "https://github.com/Frazzer951/futils"
version     = "0.3.2"

[package.metadata.wix]
upgrade-guid = "808C8A18-6A7E-4D28-88F4-5423B5B89A3C"
path-guid    = "1F39F219-9EE9-47EE-BEE5-E50079651B34"
license      = false
eula         = false

[[bin]]
name = "futils"
path = "src/main.rs"

[dependencies]
anyhow        = "1.0"
clap          = { version = "4.4", features = ["cargo"] }
clap_complete = "4.4"
fs-err        = "3.1"
serde         = { version = "1.0", features = ["derive"] }
serde_json    = { version = "1.0", features = ["preserve_order"] }
sqlparse      = "0.3"

[dev-dependencies]
tempfile = "3.8"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto      = "thin"
