[package]
authors     = ["Luke Eltiste"]
description = "A collection of command line tool that I use to make my life easier"
edition     = "2021"
license     = "MIT"
name        = "frazzers-utils"
readme      = "README.md"
repository  = "https://github.com/Frazzer951/futils"
version     = "0.1.0"

[[bin]]
name = "futils"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
